### ISSUE TITLE
Use glitch.com

### ISSUE THREAD

**Issue by Kreijstal** [Aathish04/DiscordManimator#1]
you could use glitch.com to host the discord bot

**Comment by Aathish04** [comment]
Oh, I actually considered hosting with glitch.com when I was actively hunting for places that did this sort of thing.

The reason I didn't go with glitch.com or PythonAnywhere was the same :- they only gave the user 512mb of storage, and I couldn't squeeze `manim`, with LaTeX into such a small space.

I'm actually thinking of self-hosting it, but my network is so bad that it would probably make the whole thing worse...

**Comment by Kreijstal** [comment]
> Oh, I actually considered hosting with glitch.com when I was actively hunting for places that did this sort of thing.
> 
> The reason I didn't go with glitch.com or PythonAnywhere was the same :- they only gave the user 512mb of storage, and I couldn't squeeze `manim`, with LaTeX into such a small space.
> 
> I'm actually thinking of self-hosting it, but my network is so bad that it would probably make the whole thing worse...

Hmm I didn't know that manim was that heavy
